In [1]:
import numpy as np
import pandas as pd

In [2]:
df = pd.read_csv("supply_chain_data.csv")

In [3]:
df.head()

,Warehouse_ID,Location,Current_Stock,Demand_Forecast,Lead_Time_Days,Shipping_Time_Days,Stockout_Risk,Operational_Cost,Supplier_ID,Product_Category,Monthly_Sales,Order_Processing_Time,Return_Rate,Customer_Rating,Warehouse_Capacity,Storage_Cost,Transportation_Cost,Backorder_Quantity,Damaged_Goods,Employee_Count
0,WH239,Dallas,3926,484,8,3,7,93895,S693,Groceries,4893,4.766231,6.053952,3.840976,28701,16975,2778,228,26,83
1,WH244,Houston,3032,5122,3,6,25,46847,S880,Electronics,4453,4.304335,3.886996,2.113929,36198,14052,1535,288,16,39
2,WH340,Chicago,4763,4343,5,5,16,64176,S116,Furniture,5956,1.030779,7.335160,4.211437,22784,9863,13435,153,3,49
3,WH428,Atlanta,2219,777,7,6,15,38940,S431,Apparel,5814,2.871244,1.393481,1.751671,13172,15911,14508,143,39,35
4,WH202,Dallas,809,4756,2,7,16,33933,S821,Electronics,2279,4.060930,4.212666,4.231919,39619,19011,1904,296,30,67

In [4]:
df.duplicated().sum()

np.int64(0)

In [5]:
df.isnull().sum()

Warehouse_ID             0
Location                 0
Current_Stock            0
Demand_Forecast          0
Lead_Time_Days           0
Shipping_Time_Days       0
Stockout_Risk            0
Operational_Cost         0
Supplier_ID              0
Product_Category         0
Monthly_Sales            0
Order_Processing_Time    0
Return_Rate              0
Customer_Rating          0
Warehouse_Capacity       0
Storage_Cost             0
Transportation_Cost      0
Backorder_Quantity       0
Damaged_Goods            0
Employee_Count           0
dtype: int64

In [6]:
df["Total_Delivery_Time"] = (df["Order_Processing_Time"] + df["Lead_Time_Days"] + df["Shipping_Time_Days"])

In [7]:
df["Delivery_Delay_Flag"] = df["Total_Delivery_Time"].apply(lambda x: "Normal" if x > 15 else "Delayed")

In [8]:
df["Stock_to_Demand_Ratio"] = (df["Current_Stock"] / df["Demand_Forecast"])

In [9]:
df["Logistics_Cost"] = (df["Transportation_Cost"] +df["Storage_Cost"] +df["Operational_Cost"])

In [10]:
df["Delivery_Efficiency"] = (df["Monthly_Sales"] / df["Total_Delivery_Time"])

In [11]:
def stock_category(ratio):
    if ratio < 0.9:
        return "Shortage"
    elif ratio <= 1.1:
        return "Balanced"
    else:
        return "Excess"

df["Inventory_Status"] = df["Stock_to_Demand_Ratio"].apply(stock_category)

In [12]:
df[[
"Total_Delivery_Time",
"Delivery_Delay_Flag",
"Stock_to_Demand_Ratio",
"Logistics_Cost",
"Delivery_Efficiency",
"Inventory_Status"
]].head()

,Total_Delivery_Time,Delivery_Delay_Flag,Stock_to_Demand_Ratio,Logistics_Cost,Delivery_Efficiency,Inventory_Status
0,15.766231,Normal,8.111570,113648,310.346847,Excess
1,13.304335,Delayed,0.591956,62434,334.702929,Shortage
2,11.030779,Delayed,1.096707,87474,539.943728,Balanced
3,15.871244,Normal,2.855856,69359,366.322891,Excess
4,13.060930,Delayed,0.170101,54848,174.489867,Shortage

In [13]:
df['Total_Delivery_Time'] = df['Total_Delivery_Time'].round(0).astype('int64')

In [14]:
df['Stock_to_Demand_Ratio'] = df['Stock_to_Demand_Ratio'].round(2).astype('float64')

In [15]:
df['Logistics_Cost'] = df['Logistics_Cost'].round(2).astype('float64')

In [16]:
df['Delivery_Efficiency'] = df['Delivery_Efficiency'].round(2).astype('int64')

In [17]:
df['Order_Processing_Time'] = df['Order_Processing_Time'].round(2).astype('float64')

In [18]:
df['Return_Rate'] = df['Return_Rate'].round(2).astype('float64')

In [19]:
df['Customer_Rating'] = df['Customer_Rating'].round(2).astype('float64')

In [20]:
df.columns

Index(['Warehouse_ID', 'Location', 'Current_Stock', 'Demand_Forecast',
       'Lead_Time_Days', 'Shipping_Time_Days', 'Stockout_Risk',
       'Operational_Cost', 'Supplier_ID', 'Product_Category', 'Monthly_Sales',
       'Order_Processing_Time', 'Return_Rate', 'Customer_Rating',
       'Warehouse_Capacity', 'Storage_Cost', 'Transportation_Cost',
       'Backorder_Quantity', 'Damaged_Goods', 'Employee_Count',
       'Total_Delivery_Time', 'Delivery_Delay_Flag', 'Stock_to_Demand_Ratio',
       'Logistics_Cost', 'Delivery_Efficiency', 'Inventory_Status'],
      dtype='object')

In [21]:
df.to_csv("Cleaned_supply_chain.csv", index=False)

In [22]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 500 entries, 0 to 499
Data columns (total 26 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   Warehouse_ID           500 non-null    object
 1   Location               500 non-null    object
 2   Current_Stock          500 non-null    int64
 3   Demand_Forecast        500 non-null    int64
 4   Lead_Time_Days         500 non-null    int64
 5   Shipping_Time_Days     500 non-null    int64
 6   Stockout_Risk          500 non-null    int64
 7   Operational_Cost       500 non-null    int64
 8   Supplier_ID            500 non-null    object
 9   Product_Category       500 non-null    object
 10  Monthly_Sales          500 non-null    int64
 11  Order_Processing_Time  500 non-null    float64
 12  Return_Rate            500 non-null    float64
 13  Customer_Rating        500 non-null    float64
 14  Warehouse_Capacity     500 non-null    int64
 15  Storage_Cost           500 non-null    int64
 16  Transportation_Cost    500 non-null    int64
 17  Backorder_Quantity     500 non-null    int64
 18  Damaged_Goods          500 non-null    int64
 19  Employee_Count         500 non-null    int64
 20  Total_Delivery_Time    500 non-null    int64
 21  Delivery_Delay_Flag    500 non-null    object
 22  Stock_to_Demand_Ratio  500 non-null    float64
 23  Logistics_Cost         500 non-null    float64
 24  Delivery_Efficiency    500 non-null    int64
 25  Inventory_Status       500 non-null    object
dtypes: float64(5), int64(15), object(6)
memory usage: 101.7+ KB

In [23]:
df.head()

,Warehouse_ID,Location,Current_Stock,Demand_Forecast,Lead_Time_Days,Shipping_Time_Days,Stockout_Risk,Operational_Cost,Supplier_ID,Product_Category,...,Transportation_Cost,Backorder_Quantity,Damaged_Goods,Employee_Count,Total_Delivery_Time,Delivery_Delay_Flag,Stock_to_Demand_Ratio,Logistics_Cost,Delivery_Efficiency,Inventory_Status
0,WH239,Dallas,3926,484,8,3,7,93895,S693,Groceries,...,2778,228,26,83,16,Normal,8.11,113648.0,310,Excess
1,WH244,Houston,3032,5122,3,6,25,46847,S880,Electronics,...,1535,288,16,39,13,Delayed,0.59,62434.0,334,Shortage
2,WH340,Chicago,4763,4343,5,5,16,64176,S116,Furniture,...,13435,153,3,49,11,Delayed,1.10,87474.0,539,Balanced
3,WH428,Atlanta,2219,777,7,6,15,38940,S431,Apparel,...,14508,143,39,35,16,Normal,2.86,69359.0,366,Excess
4,WH202,Dallas,809,4756,2,7,16,33933,S821,Electronics,...,1904,296,30,67,13,Delayed,0.17,54848.0,174,Shortage